### ISSUE TITLE
Enable network policy for flux

### ISSUE THREAD

**Issue by jfroy** [jfroy/flatops#20]
Copied from [onedr0p/home-ops](https://github.com/onedr0p/home-ops):

```yaml
    # Remove the network policies that does not work with k3s
    - patch: |
        $patch: delete
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: not-used
      target:
        group: networking.k8s.io
        kind: NetworkPolicy
```
