### ISSUE TITLE
Maybe add V6 CIDR to `validSubnets` in talconfig

### ISSUE THREAD

**Issue by jfroy** [jfroy/flatops#207]
```
        nodeIP:
          validSubnets:
            - 192.168.1.0/27
```

**Comment by jfroy** [comment]
Also possibly to etcd configuration:

```
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - 192.168.1.0/27
```
