### ISSUE TITLE
Add `KubePrism` patch to talconfig

### ISSUE THREAD

**Issue by jfroy** [jfroy/flatops#208]
```
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
```

See https://www.talos.dev/v1.7/kubernetes-guides/configuration/kubeprism/
