### ISSUE TITLE
Send talos logs to cluster observability stack

### ISSUE THREAD

**Issue by jfroy** [jfroy/flatops#209]
Via a machine patch:

```
      machine:
        logging:
          destinations:
            - endpoint: udp://vector....
              format: json_lines
```
