### ISSUE TITLE
Evaluate nameserver talos machine patch

### ISSUE THREAD

**Issue by jfroy** [jfroy/flatops#210]
```
      machine:
        network:
          nameservers:
            - xxx
```

Not sure this is needed but some k8s-home clusters have it.
